version: "3.8"

services:

  continuous-curl-runner-random:
    image: ${REG}continuous-curl-runner:${TAG}
    volumes:
      - ./sample-requests.json:/sample-requests.json:ro
    environment: 
      CURL_OPTS: "--insecure"
      REQUESTS_JSON_FILE: /sample-requests.json
      REQUESTS_INTERVAL: "5"
      REQUESTS_SELECTION: "random"
      test_user: "some_user"
      test_password1: "passwd1"
      test_password2: "passwd2"
      test_password3: "passwd3"

  continuous-curl-runner-sequential:
    image: ${REG}continuous-curl-runner:${TAG}
    volumes:
      - ./sample-requests.json:/sample-requests.json:ro
    environment: 
      CURL_OPTS: "--insecure"
      REQUESTS_JSON_FILE: /sample-requests.json
      REQUESTS_INTERVAL: "20"
      REQUESTS_SELECTION: "sequential"
      REQUESTS_SEQUENTIAL_INTERVAL: "2"
      test_user: "some_user"
      test_password1: "passwd1"
      test_password2: "passwd2"
      test_password3: "passwd3"