{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "continuous-curl-runner.fullname" . }}
  labels:
    {{- include "continuous-curl-runner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "continuous-curl-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "continuous-curl-runner.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      serviceAccountName: {{ include "continuous-curl-runner.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}"
          {{- if .Values.image.registry }}
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) }}
          {{- else }}
          image: {{ printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            {{- range $name, $value := .Values.envSecrets }}
            - name: {{ $name | quote }}
              valueFrom:
                secretKeyRef:
                  name: "{{ template "continuous-curl-runner.fullname" $ }}"
                  key: {{ $name | quote }}
            {{- end }}
            {{- range $name, $value := .Values.envExistingSecrets }}
            - name: {{ $name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretKeyRef | quote }}
                  key: {{ $value.key | quote }}
            {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
{{- end }}
